project:
  type: website
  output-dir: docs

website:
  title: "Leena Soo"
  navbar:
    left:
      - href: index.qmd
        text: About
      - project.qmd
        

format:
  html:
    theme: jolla
    css: styles.css
    toc: true
    include-after-body: _footer.html



