project:
  type: website
  output-dir: docs

website:
  title: "Profile"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - project.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



